name: Codacy Coverage Reporter

on:
  push:
    # Codacy always requests the latest coverage report 
    # from the most recent commit, even if it is out of context.
    branches: [ "main", "dev" ]

permissions:
  contents: read

env:
  MIN_PYTHON_VERSION: "3.10"  # Use the minimum supported Python version for coverage generation

jobs:
  coverage-reporter:

    runs-on: ubuntu-latest

    name: codacy-coverage-reporter

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Python ${{ env.MIN_PYTHON_VERSION }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: ${{ env.MIN_PYTHON_VERSION }}

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Generate coverage report with pytest
        run: pytest --cov=onvif --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699  # v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
